### ISSUE TITLE
Gallery crashes when offline

### ISSUE THREAD

**Issue by groaking** [gkisalatiga/gki-salatiga-plus#37]
### How to reproduce

1. Close the application (ensure it is not running in background)
2. Turn off all connectivity (Wi-Fi, data package, etc.)
3. Re-open GKI Salatiga+
4. Open "Gallery" menu
5. The application crashes

The latest LOG_CAT message is as follow:

```
java.lang.NullPointerException
	at org.gkisalatiga.plus.screen.ScreenGaleri.getMainContent(ScreenGaleri.kt:94)
	at org.gkisalatiga.plus.screen.ScreenGaleri.access$getMainContent(ScreenGaleri.kt:65)
	at org.gkisalatiga.plus.screen.ScreenGaleri$getComposable$2.invoke(ScreenGaleri.kt:76)
	at org.gkisalatiga.plus.screen.ScreenGaleri$getComposable$2.invoke(ScreenGaleri.kt:72)
```

**Comment by groaking** [comment]
Sudah difix di commit 2aa44d6 bang. Sekarang sudah bisa buka galeri pas offline.
